apiVersion: 1

datasources:
  - name: SQLite_Analytics
    type: frser-sqlite-datasource
    access: proxy
    url: /var/lib/grafana/data/streaming_analytics.db
    isDefault: true
    editable: true
